version: '3.9'

services:
  postgres_users:
    image: postgres:16
    container_name: postgres_users
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: ['CMD', 'pg_isready -q -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - 5454:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - bot

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s # Максимальное время выполнения
      retries: 3
      start_period: 10s
    ports:
      - 6379:6379
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - bot

  
volumes:
  pg-data:
  redis-data:

networks:
  app:
    driver: bridge